name: hello_flutter
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  google_fonts: ^2.1.0
  provider: ^6.0.1

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#214555"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
